package client;

import com.example.grpc.SimpleSumGrpc.SimpleSumImplBase;
import com.example.grpc.Sum.*;
import io.grpc.stub.StreamObserver;

/**
 * Simple sum class, it extends the boilerplate generated by the GRPC framework for Java
 */
public class SimpleSum extends SimpleSumImplBase {
    /**
     * Simple sum method that returns the sum between two numbers receiver through the req parameter.
     * 
     * @param req The object is defined inside the .proto file, it contains two fields which are the first and the second term of the sum. 
     * @param streamObserver The object that is used to allow the caller to react to events.
     */
    @Override
    public void streamSimpleSum(SimpleSumRequest req,
                                StreamObserver<SimpleSumResponse> streamObserver){
        System.out.print(req.getN1() + " + " + req.getN2());

        SimpleSumResponse sumResponse = SimpleSumResponse.newBuilder()
                .setSum(req.getN1() + req.getN2())
                .build();

        streamObserver.onNext(sumResponse);
        streamObserver.onCompleted();
    }
}
